# Generated by Django 4.2.9 on 2024-12-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0025_csvupload_name_alter_csvupload_week'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVUpload',
        ),
    ]
